name: Create a (Pre)release on NuGet

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"
jobs:
  release-nuget:
  
    runs-on: windows-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Get version information from tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release /p:Version=${{ steps.get_version.outputs.version-without-v }}

      - name: Pack
        run: >
          dotnet pack
          -p:ContinuousIntegrationBuild=true
          -c Release
          /p:Version=${{ steps.get_version.outputs.version-without-v }}

      - name: Push packages
        run: >
          dotnet nuget push **/*.nupkg
          --source "https://api.nuget.org/v3/index.json"
          --api-key ${{ secrets.NUGET_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_TOKEN }}